<?php

namespace App\Support;

/**
 * Minimal OOXML (.xlsx) writer that does not require ext-zip.
 * Builds a zip archive with store/deflate entries (same approach as SimpleXLSXGen).
 */
class XlsxZipBuilder
{
    /**
     * @param  array<string, string>  $files  path => XML/content
     */
    public function build(array $files): string
    {
        $fh = fopen('php://memory', 'wb+');
        if ($fh === false) {
            throw new \RuntimeException('Unable to allocate memory for Excel file.');
        }

        $cdrec = '';
        $entries = 0;

        foreach ($files as $path => $data) {
            $this->writeEntry($fh, $cdrec, $path, $data);
            $entries++;
        }

        $beforeCd = ftell($fh);
        fwrite($fh, $cdrec);

        $comment = 'Generated by FinProms';
        fwrite($fh, "\x50\x4b\x05\x06");
        fwrite($fh, pack('v', 0));
        fwrite($fh, pack('v', 0));
        fwrite($fh, pack('v', $entries));
        fwrite($fh, pack('v', $entries));
        fwrite($fh, pack('V', strlen($cdrec)));
        fwrite($fh, pack('V', $beforeCd));
        fwrite($fh, pack('v', strlen($comment)));
        fwrite($fh, $comment);

        rewind($fh);
        $binary = stream_get_contents($fh) ?: '';
        fclose($fh);

        return $binary;
    }

    /**
     * @param  resource  $fh
     */
    private function writeEntry($fh, string &$cdrec, string $filename, string $data): void
    {
        $uncsize = strlen($data);
        if ($uncsize < 256) {
            $zdata = $data;
            $cmethod = 0;
            $comsize = $uncsize;
        } else {
            $zdata = substr(gzcompress($data), 2, -4);
            $cmethod = 8;
            $comsize = strlen($zdata);
        }

        $crc = crc32($data);
        $date = getdate();
        $dostime = (
            (($date['year'] - 1980) << 25)
            | ($date['mon'] << 21)
            | ($date['mday'] << 16)
            | ($date['hours'] << 11)
            | ($date['minutes'] << 5)
            | ($date['seconds'] >> 1)
        );

        $offset = ftell($fh);
        $nameLen = strlen($filename);

        fwrite($fh, "\x50\x4b\x03\x04");
        fwrite($fh, pack('v', 20));
        fwrite($fh, pack('v', 0));
        fwrite($fh, pack('v', $cmethod));
        fwrite($fh, pack('V', $dostime));
        fwrite($fh, pack('V', $crc));
        fwrite($fh, pack('V', $comsize));
        fwrite($fh, pack('V', $uncsize));
        fwrite($fh, pack('v', $nameLen));
        fwrite($fh, pack('v', 0));
        fwrite($fh, $filename);
        fwrite($fh, $zdata);

        $cdrec .= "\x50\x4b\x01\x02";
        $cdrec .= pack('v', 0);
        $cdrec .= pack('v', 20);
        $cdrec .= pack('v', 0);
        $cdrec .= pack('v', $cmethod);
        $cdrec .= pack('V', $dostime);
        $cdrec .= pack('V', $crc);
        $cdrec .= pack('V', $comsize);
        $cdrec .= pack('V', $uncsize);
        $cdrec .= pack('v', $nameLen);
        $cdrec .= pack('v', 0);
        $cdrec .= pack('v', 0);
        $cdrec .= pack('v', 0);
        $cdrec .= pack('v', 0);
        $cdrec .= pack('V', 32);
        $cdrec .= pack('V', $offset);
        $cdrec .= $filename;
    }
}
